//
//  ColorLibrary.swift
//
//  Created on 06/01/2017.
//
//  Generated by PaintCode Plugin for Sketch
//  http://www.paintcodeapp.com/sketch
//

import UIKit



class ColorLibrary: NSObject {
    
    
    //MARK: - Colors
    
    static let themeColor = UIColor(hue: 0.246, saturation: 0.843, brightness: 0.826, alpha: 1)
    
    
}
